name: Build Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SCHEME: DevOpsPractical6

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.2.0

      - name: Build iOS
        run: |
          xcodebuild -project $SCHEME.xcodeproj -scheme "$SCHEME" clean build \
          -sdk iphoneos -destination generic/platform=iOS CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED="NO" | xcpretty --color
      - name: Test iOS
        run: |
          xcodebuild test -project $SCHEME.xcodeproj -scheme "$SCHEME" clean build \
          -sdk iphoneos -destination generic/platform=iOS CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED="NO" | xcpretty --color 
